-- Users table: stores authenticated users (populated via Google OAuth)
create table if not exists "Users" (
  id bigint generated by default as identity primary key,
  email text unique not null,
  name text,
  picture text,
  created_at timestamptz default now()
);

-- Interviews table: stores AI-generated visa interview sessions
create table if not exists "Interviews" (
  id bigint generated by default as identity primary key,
  interview_id uuid not null default gen_random_uuid(),
  country text not null,
  description text,
  duration text,
  questions jsonb,
  user_email text references "Users" (email) on delete cascade,
  created_at timestamptz default now()
);

-- Enable Row Level Security
alter table "Users" enable row level security;
alter table "Interviews" enable row level security;

-- RLS: users can only read/write their own row
create policy "Users: select own" on "Users"
  for select using (auth.jwt() ->> 'email' = email);

create policy "Users: insert own" on "Users"
  for insert with check (auth.jwt() ->> 'email' = email);

-- RLS: users can only read/write their own interviews
create policy "Interviews: select own" on "Interviews"
  for select using (auth.jwt() ->> 'email' = user_email);

create policy "Interviews: insert own" on "Interviews"
  for insert with check (auth.jwt() ->> 'email' = user_email);
